spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybooks
    username: mybooks
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  url: http://localhost:8080/api/books

